name: vnphanquang
services:
  vnphanquang.com:
    image: vnphanquang.com
    pull_policy: build
    build:
      context: .
      dockerfile: dockerfile
      target: vnphanquang.com
    environment:
      - UMAMI_SCRIPT_URL=""
      - UMAMI_WEBSITE_ID=""
    ports:
      - 3500:3000
    restart: unless-stopped
