packages:
  - 'packages/*'
  - 'sites/*'
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - svelte-md-template
  - remark-enhance-codeblock
  - remark-transform-blockquote
  - '@sveltejs/kit'
  - '@sveltejs/adapter-node'
