name: Monkeytype Readme

on:
  workflow_dispatch:
  schedule:
    # At 00:00 on Sunday
    - cron: '0 0 * * 0'
  # push:
  #     branches:
  #       - master
  #     paths:
  #       - ".github/workflows/monkeytype.yaml"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: vnphanquang/monkeytype-readme@main
        with:
          monkeytype_api_key: ${{ secrets.MONKEYTYPE_API_KEY }}
          mode: 'words'
          mode2: '50'
          style: 'for-the-badge'
          logoVariant: 'one'
          label: 'monkeytype'
